// Stoatworks Labs — About window data for Show Mode.
//
// GENERATED by stoatworks-backend/scripts/sync-about.py on 2026-09-29. Do not
// edit: the next sync overwrites it. The facts come from the website's
// projects.json, which is the one place they are written down.
//
// `version` here is a fallback read from this repo's own manifest at sync
// time. Anything with a build step injects the real one at build time and
// overrides this.

enum StoatworksAboutData {
    static let name = "Show Mode"
    static let slug = "showmode"
    static let hook = "One click to lock a Mac down for a show"
    static let licence = "MIT"
    static let guide = "https://stoatworks-labs.com/software/showmode/guide/"
    static let page = "https://stoatworks-labs.com/software/showmode/"
    static let repo = "https://github.com/stoatworks-labs/showmode"
    static let versionFallback = "v0.3.0"

    static let org = "Stoatworks Labs"
    static let home = "https://stoatworks-labs.com"
    static let tagline = "Open tools for the people who run the show."

    /// The canonical funding links, matching FUNDING.yml and the support footer.
    static let funding: [(String, String)] = [
        ("GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs"),
        ("Ko-fi", "https://ko-fi.com/stoatworkslabs"),
        ("Patreon", "https://patreon.com/StoatworksLabs"),
        ("Liberapay", "https://liberapay.com/stoatworks-labs"),
    ]
}
